application: boxscore-junkie
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img

- url: /
  script: home.py

- url: /calendar
  script: main.py

- url: /faq.html
  static_files: html/faq.html
  upload: html/faq.html

- url: (/scoreboard|/boxscore|/playbyplay|/pitchbypitch|/pitcherpbp|/batterpbp|/highlights)
  script: core.py

- url: /fetch/.*
  script: fetch.py

- url: /data/team/.*
  script: db_admin.py

- url: /data/player/.*
  script: db_player.py

- url: /*
  script: not_found.py